---
minor_changes:
  - Add an action group for the collection modules ``kv1_secret``, ``kv1_secret_info``, ``kv2_secret``, ``kv2_secret_info``
    (https://github.com/ansible-collections/hashicorp.vault/pull/23).
  - kv2_secret_info - module will not fail when the requested secret does not exists instead returns an empty response
    (https://github.com/ansible-collections/hashicorp.vault/pull/23).
