---
requires_ansible: ">=2.16.0"
action_groups:
  vault:
    - acl_policy
    - acl_policy_info
    - auth_login
    - auth_token
    - auth_token_info
    - database_connection
    - database_connection_info
    - database_credential_rotation
    - database_dynamic_role_credentials
    - database_role
    - database_role_info
    - database_static_role
    - database_static_role_info
    - database_static_role_credentials
    - kv1_secret
    - kv1_secret_info
    - kv2_secret
    - kv2_secret_info
    - pki_certificate
    - pki_certificate_info
    - vault_namespace
    - vault_namespace_info
