---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-test-secret
  namespace: vso-test
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: test/vso-integration
  refreshAfter: 10s
  destination:
    name: vso-synced-secret
    create: true

